development:
  sessions:
    default:
      database: wall_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: wall_test
      hosts:
        - localhost:27017
      options:
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      #uri: <%= ENV['MONGOHQ_URL'] %>
      database: wallalemana
      hosts:
        - $OPENSHIFT_MONGODB_DB_HOST:$OPENSHIFT_MONGODB_DB_PORT
      username: admin
      password: dGaKsbGkMPBc
      options:
        skip_version_check: true
        safe: true