development:
  sessions:
    default:
      database: wall_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: wall_test
      hosts:
        - localhost:27017
      options:
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: mongodb://admin:dGaKsbGkMPBc@127.5.0.130:27017/wallalemana
      #database: wallalemana
      #hosts:
      #  - 127.5.0.130:27017
      #username: admin
      #password: dGaKsbGkMPBc
      options:
        skip_version_check: true
        safe: true